version: '2.2'

services:

  interview-localstack:
    image: localstack/localstack
    container_name: localstack_aws
    ports:
      - "4567-4597:4567-4597"
      - "4566:4566"
    environment:
      - DEFAULT_REGION=ap-southeast-1
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      app_network:
        ipv4_address: 172.20.0.2
      
  database-setup:
    image: amazon/dynamodb-local
    container_name: awslocaldb
    ports:
      - "8000:8000"
    networks:
      app_network:
        ipv4_address: 172.20.0.3
networks:
  app_network:
    name: sqsapp-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
